### ISSUE TITLE
Aggregated metrics sometimes are not correct

### ISSUE THREAD

**Issue by pgul** [graphite-project/carbon#109]
In some rare cases aggregated metrics are much less then sum() of its components.

This caused when carbon-aggregator sends the same metric/timestamp to carbon-cache more then once with different values (partially collected and then final value), these values queued by carbon-cache, fetched from queue by one pop() call, and stored by one whisper.update_many() call. Whisper sort these datapoints by timestamps, and it's possible that within the same timestamp earlier (partial) aggregated metric will be stored in wsp file instead of final value.

Using branch 0.9.x.

Proposed patch:

<pre>
--- lib/carbon/cache.py.orig    2013-04-01 07:10:51.000000000 +0000
+++ lib/carbon/cache.py 2013-05-29 03:55:10.000000000 +0000
@@ -64,5 +64,6 @@
     elif not metric and self.method == "sorted":
       metric = self.queue.next()
-    datapoints = (metric, super(_MetricCache, self).pop(metric))
+    # Save only last value for each timestamp
+    datapoints = (metric, sorted(dict(super(_MetricCache, self).pop(metric)).items(), key=lambda x:x[0]))
     return datapoints
</pre>

**Comment by mikegong** [comment]
Is the the problem brought by @genisd addressed by fix #240? It seems not.

**Comment by Neway6655** [comment]
I met another issue, related to this one: I have two sum aggregators, let's say aggregatorA, and aggregatorB, the aggregated result by aggregatorA will be passed to aggregatorB as the input.

And we have 60k metrics per second sent to aggregatorA from 6 nodes, which causes aggregatorA's cpu usage closed to 100%, and the same metric/timestamp will be handled by aggregatorA at different time(I guess this is caused by the 100% cpu usage), so aggregatorA will do several aggregate operations, let's say twice aggregations, the result are: first time, timestamp: t0, value: 10; second time, timestamp t0, value: 15. And we know that 15 the correct result, and it works well if we send the results to carbon-cache, with fix #240 , but the problem comes out when we send the results to aggregatorB, as for aggregatorB, it will receive both these two metrics generated by aggregatorA, and it will sum those two results together as aggregatorB's result, which is 25, in this case, but what we wanted is 15.

The reason why we use two aggregators is that, there are so many metrics received per second, and we have 3 fields need to be aggregated, so we want to aggregate one field first, and only keep the first aggregated result as the input for the second aggregator, so there are much less metrics need to be handled by the second aggregator.

Thanks for any suggestions!

**Comment by svenmueller** [comment]
in which version is this fix contained?

**Comment by deniszh** [comment]
@svenmueller - IMO only 0.9.13-pre1 - https://github.com/graphite-project/carbon/releases/tag/0.9.13-pre1
