### ISSUE TITLE
Carbon cache:  no module named carbon.util

### ISSUE THREAD

**Issue by tristanbes** [graphite-project/carbon#276]
I'm on the `master` verison for graphite / cabron and whisper

I did 3 install of graphite/carbon:
- 2 installation 14 days ago : it's all okay
- 1 installation today : it's failing to start carbon

```
/opt/graphite/bin/python /opt/graphite/bin/carbon-cache.py --debug start
Traceback (most recent call last):
  File "/opt/graphite/bin/carbon-cache.py", line 28, in <module>
    from carbon.util import run_twistd_plugin
ImportError: No module named carbon.util
```

The installation is automated via ansible, so basically the installation process is the same than I did 2 weeks ago (on Debian 7.6 x64)

**Comment by jgwinner** [comment]
I just ran into the same thing :( Also, stuff was scattered around a little; instead of /opt/graphite/bin/carbon-cache.py I had to use /usr/local/bin/carbon-cache.py

I used pip2.7 install carbon (etc)

I haven't tried installing from source.

python2.7 is installed (CentOS/Oracle Linux), but 2.6 is still the default. I'm using pip2.7 and python2.7 in /usr/local to run carbon (hopefully, as it won't work with 2.6).
