### ISSUE TITLE
File generated when disk is full are corrupted

### ISSUE THREAD

**Issue by lyrixx** [graphite-project/carbon#327]
I just noticed we have few empty TS in our graphite server

Actually, files was empty, without headers:

    CorruptWhisperFile: Unable to read header (/opt/graphite/storage/whisper/stats/application/com/sensiolabs/insight/http/response/status-code/200.wsp)

I guess (not sure) it happens because the disk was full. So only an empty was created.

How to detect that?

    find  /opt/graphite/storage/whisper/ -type f -empty 

How to fix that?

    find  /opt/graphite/storage/whisper/ -type f -empty -delete

**Comment by garrettwilkin** [comment]
I've run into this same issue. :(  I'm going to delete those corrupt files and start again.

It appears that I've lost a bunch of data, due to this series of events:

1. The files were created when the disk was full, without headers.
1. I fixed the disk issue
1. Since there was no header on many of the files, all further metrics were lost.

I only discovered this because I checked disk usage in `graphite/storage` and saw that my `carbon-cache/carbon-cache-a/console.log_2015_06_25.log` file was 7GB.

:sob:

**Comment by obfuscurity** [comment]
Yes, you should be monitoring your disk for capacity. Any attempted creates will fail and further metrics will be lost. *Existing* whisper files will resume writes once capacity is available (assuming the metrics are still in the buffer). This is a non-issue and no different from virtually any other service that has to write metadata when writing files to UNIX.
