### ISSUE TITLE
Is LOG_AGGREGATOR_MISSES configuration directive used anywhere in code?

### ISSUE THREAD

**Issue by zdenekpizl** [graphite-project/carbon#396]
Hi,

 I've just started to use carbon-aggregator and it logs huge amount of metrics not matching aggregation rules. I'd like to switch this extensive logging off but LOG_AGGREGATOR_MISSES directive does not work apparently.

After simple search through code, it looks there is only assignment of default value but there is not any code block to process this setting.

Is it intentional? Thank you, .zp.

**Comment by obfuscurity** [comment]
It was introduced [here](https://github.com/graphite-project/carbon/commit/8ae7254d77581c7fb98cf6c5fd1fe19e993d2bad) but then receiver.py was removed as part of this [megacarbon refactor](https://github.com/graphite-project/carbon/commit/88a646441cabf7def6721546c62ef19e5a1c7e1e) back in January. It looks like the logging bits were never recreated.

@mleinart was this intentional and we just need to clear out the remaining references to `LOG_AGGREGATOR_MISSES` or should that log be added back?
