### ISSUE TITLE
init.d scripts do not return correct exit status for service running/stopped

### ISSUE THREAD

**Issue by alecxvs** [graphite-project/carbon#414]
Running `/opt/graphite/bin/carbon-cache.py status` will print that the service is not running and exits with a status of 1 as expected.
Executing `/etc/init.d/carbon-cache status` or `service carbon-cache status` will print that the service is not running **but exits with a status of 0**.
Automated services such as Chef depend on this exit code returning truthfully.

**Comment by aidos** [comment]
This is all pretty unfamiliar ground for me but after trawling around init.d scripts it seems like basically nobody (other than postgres, of course) are honouring [the exit codes in here](http://refspecs.linuxbase.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html).

I'm actually looking into this because `service nginx configtest` always returns `0` (while `/usr/sbin/nginx -t` does the right thing). Further investigation has revealed that it's totally normal to not return a useful exit code.

Anyways, I don't really care about it in the carbon case (at the moment) but [I've posted a general question over here](http://unix.stackexchange.com/questions/318666/are-most-init-d-scripts-returning-the-wrong-exit-codes) in the hopes that someone can explain what's going on.
