### ISSUE TITLE
carbon cache

### ISSUE THREAD

**Issue by Himanshu-pupneja** [graphite-project/carbon#521]
Hi,

I am using carbon with graphite. i need a clarity on update metrics.

I have set the value of "**MAX_UPDATES_PER_SECOND**" is **500**. so metrics can be updated in a minute is "**30K**".
When the metrics crosses this limit, carbon caching take effect.
So my que is, 
**Is there any data loss if my metrics exceeds threshold value? or what happened which the metrics exceeds?**

Thanks & Regards,
Himanshu

**Comment by eqinox76** [comment]
Carbon should start to buffer your data in memory until MAX_CACHE_SIZE is reached.

See also this parameter:
# Set this to False to drop datapoints received after the cache
# reaches MAX_CACHE_SIZE. If this is True (the default) then sockets
# over which metrics are received will temporarily stop accepting
# data until the cache size falls below 95% MAX_CACHE_SIZE.
USE_FLOW_CONTROL = True

Hope this helps.

**Comment by Himanshu-pupneja** [comment]
Hi Carsten,

Thanks for your kind response.

In my environment data is in very large amount and "MAX_CACHE_SIZE" set to infinity.
And machine cache memory is always on peak(full).
I am not sure my data is getting loss or not.

Is there any better way that i can do?

Thanks
Himanshu

**Comment by obfuscurity** [comment]
The most effective way to handle a lot of datapoints (i.e. when the volume of datapoints exceeds the IOPS capacity for your Graphite server) is to coerce Graphite (Carbon) into performing bulk updates (many datapoints flushed per write operation). This should occur when Carbon is configured to:

* Limit memory by setting `MAX_CACHE_SIZE` to a non-`inf` value. This setting represents the number of datapoints to hold in (each respective) cache. If you leave it to `inf`, Carbon will attempt to store all datapoints in memory. Aside from the implications of unbounded application memory causing a kernel panic, it means that shutting down your carbon-cache(s) could take a very long time since it would need to write all of the in-memory datapoints to (presumably) a slow disk.
* Limit write operations by setting `MAX_UPDATES_PER_SECOND` to a value **less than** the current volume of metrics/second received by Carbon. For example, if you're receiving 10k datapoints per second, setting `MAX_UPDATES_PER_SECOND=1000` should result in the cache attempting to write 10 datapoints with each write operation. Of course this is theoretical and highly dependent on your particular hardware specification. If you read [this post from my blog](http://obfuscurity.com/2016/08/Benchmarking-Carbon-and-Whisper-on-AWS) you'll see I managed to write 60k metrics/second on a single Graphite server by leveraging all of the available CPU cores, running **8 carbon-caches** behind **6 carbon-relays** behind HAProxy.

Note that the **pointsPerUpdate** metric (e.g. `carbon.agents.carbon-cache-0.pointsPerUpdate`) will help you measure the effectiveness of your batch writes. Using the aforementioned example, I would expect to see a `pointsPerUpdate` of approximately 10.

**Comment by satish-chef** [comment]
@obfuscurity I read your comment and your blog and I found them very interesting.  I have been tinkering with carbon-cache and carbon-relay setting since last two weeks to reduce metric drops.
Below is the content of /opt/graphite/conf/carbon.conf on the Graphite server:
