### ISSUE TITLE
Carbon cache slows down

### ISSUE THREAD

**Issue by z710x40** [graphite-project/carbon#681]
L.S.
We have a strange issue. We have 16 carbon caches running. And for an unknown reason the cache number 12 is failing. The relay is reporting connection time outs. The graphite is reporting query time outs.
The logging of the cache itself shows invalid lines (some are sending a lot of them) and sometimes lost connections. The other caches only show invalid lines.
Cache number 12 seems to keep on functioning by receiving metrics but.
A restart helps for a while but after a couple of hours the cache starts to slow down again until onther restart. 
Restarting via the service command doesn't work. We really have to kill the process before the service can be started again.
 
Does anybody has a clue what could be the problem here?

**Comment by piotr1212** [comment]
Which carbon, os, Python version are you using? What is the memory and cpu
usage of the caches?

Op di 22 aug. 2017 06:41 schreef z710x40 <notifications@github.com>:

**Comment by z710x40** [comment]
Python is 2.6 on RHEL7. The cache uses a lot of CPU around 100% of one of the 13 PCU. The average of the other caches is around 20 to 30%.
It also seems to happen when there a lot of invalid lines received

**Comment by piotr1212** [comment]
Sounds familiar to me. Is the memory usage of the hanging cache larger than the others? If this is the same issue I experienced it was because of an issue in Python 2.6 which causes the garbage collection time to increase non-linear (in terms of memory size). If your cache size's get bigger GC takes more time, which causes the cache become even bigger. carbon_ch (consistent hashing algorithm) is known for not distributing the metrics evenly which can explain why some cache's get bigger and start showing this. Possible solutions: Update Python to 2.7 (fixes the non-linear GC) or even better PyPy. Double the number of caches you have (this will result in lower memory usage per cache, thus less GC time). Increase max_updates_per_second which lowers cache sizes. Or you could try https://github.com/lomik/go-carbon which doesn't use Python at all.

**Comment by z710x40** [comment]
Clear. Then we first need to update and then check again.
Thanx for the help
