### ISSUE TITLE
[Carbon-Relay] Number of open file descriptors continuously increases

### ISSUE THREAD

**Issue by Mskeffington** [graphite-project/carbon#685]
I'm running Graphite on Ubuntu 14.04 in a production environment where <tens> of thousands of devices are all reporting metrics.  Carbon-Relay doesn't seem to gracefully handle closing file descriptors so after about 2 weeks, the process hits 65535 open descriptors and locks up.  Restarting the carbon-relay service resets the number of open file descriptors and gets me up and running again.

Not sure what configuration outputs I can share to help.

**Comment by deniszh** [comment]
I'm not aware of any file descriptor leak in the current code. OTOH I do not run python relay for a long time already... Please note that you can process the only limited amount of metrics on the single relay because single python process is hardly scalable. So, I suspecting it's just overloaded and constantly reconnecting to caches and/or clients.
So, if you have huge metric stream then you should run multiple python relays behind the load balancer - or use alternative routers - https://github.com/grobian/carbon-c-relay (written in C) or https://github.com/graphite-ng/carbon-relay-ng (written in Go).

**Comment by piotr1212** [comment]
Are the descriptors pointing to files or are those lingering network sockets?

**Comment by Mskeffington** [comment]
The file descriptors are for lingering network sockets.

**Comment by piotr1212** [comment]
if it is what I am suspecting this commit might help: https://github.com/piotr1212/carbon/commit/bed0dc3da65d0fd237e6d5808aa4dbfb73126aa9 Could you please check if it solves your problems?
