### ISSUE TITLE
[Feature Request] Endpoint for storing and retrieving metric descriptions

### ISSUE THREAD

**Issue by xkilian** [graphite-project/carbon#697]
Storing metrics is fine.
Storing tags is fine.
But what does a metric mean...

Ex: MS Proxy perfmon counter

_Average request speed_

>  The average speed of the request for all requests in the  previous minute. The speed is calculated by dividing the request size by  the time needed to serve the request, and is provided in bytes per  second.

This data should be available in frontends like grafana, for data stored in a backend like Graphite. Asking for endpoint /description?metric=metric.name  would return text with the explanation for the counter. This would make it easier for frontends to include this feature by default. 

Data could be submitted via a special endpoint /description with metric.name "description"

This is to get the idea out there. Metric names or even tags do not always hold the key as to what the heck something really is!

**Comment by deniszh** [comment]
First - this issue is not for carbon - carbon will not store this info. Descriptions should be stored somewhere else, so graphite-web should support it instead.
But in general I don't thonk that's a good idea. IMO single metric very rately has sense - usually you apply some finctions to it to get a graph, right? And usually you need to describe graph - but that support is already in Graphana.
Also, yoi need some flexible way how to store descriotions, like we doing for tags. Really not sure tgat's really worth it.
Sorry for typos, writing from phone.
