### ISSUE TITLE
Proposal: remove all prefix and ROOT_DIR detection logic from carbon

### ISSUE THREAD

**Issue by baverman** [graphite-project/carbon#719]
I don't understand why carbon should be special and wants to be installed in /opt. Let's drop this additional code and use simple python packaging. I can do PR.

**Comment by deniszh** [comment]
Hello @baverman,
We're glad to accept PRs, sure!
Please also note, that this fix should be done not only to carbon but also for whisper and graphite-web. It also should be backward compatible for the easy upgrade, and applicable to virtualenv too.
Currently, carbon wants to be installed in /opt, but can be installed in different place - 

```
GRAPHITE_HOME=...
virtualenv "$GRAPHITE_HOME"
mkdir "$GRAPHITE_HOME/webapp"
source "$GRAPHITE_HOME/bin/activate"
export PYTHONPATH="$GRAPHITE_HOME/lib/:$GRAPHITE_HOME/webapp/"
pip install six
GRAPHITE_NO_PREFIX=True pip install --no-binary=:all: whisper carbon graphite-web
```
But it's not ideal - in virtualenv in installs graphite-web to `$GRAPHITE_HOME/lib/python2.7/site-packages` instead of `$GRAPHITE_HOME/webapp`. :(
