### ISSUE TITLE
protobuf doesn't support tags

### ISSUE THREAD

**Issue by Civil** [graphite-project/carbon#736]
https://github.com/graphite-project/carbon/blob/master/lib/carbon/carbon.proto

tag support is missing.

**Comment by deniszh** [comment]
Yes, indeed. @iksaif, are you using protobuff, right? IIRC you said that you will add tags support soon, am I right?

**Comment by iksaif** [comment]
Yes, tag support should be added before end of February, you can assign this one to me

**Comment by DanCech** [comment]
Won't it work transparently with tagged metrics like standard line protocol etc?On Jan 15, 2018 6:18 AM, Corentin Chary <notifications@github.com> wrote:Yes, tag support should be added before end of February, you can assign this one to me

**Comment by iksaif** [comment]
Likely, I haven't tested though.

**Comment by iksaif** [comment]
Ok checked, and because protobuf just uses "metricReceived" it will work. The metric name can use the carbon format: http://graphite.readthedocs.io/en/latest/tags.html#carbon and should work with the openmetrics format too : https://github.com/RichiH/OpenMetrics/blob/master/metric_exposition_format.md

It would be nicer to have tags exposed in the protobuf message, I'll try to add that later.
