### ISSUE TITLE
Log spew "Unhandled error in Deferred:"

### ISSUE THREAD

**Issue by reyjrar** [graphite-project/carbon#742]
Just upgraded a node from 1.0.2 to 1.1.1 and now this is streaming into my log files at a rate of 16/sec:

```
31/01/2018 18:34:13 :: Unhandled error in Deferred:
31/01/2018 18:34:13 :: Unhandled Error
Traceback (most recent call last):
Failure: twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.

31/01/2018 18:34:13 :: Unhandled error in Deferred:
31/01/2018 18:34:13 :: Unhandled Error
Traceback (most recent call last):
Failure: twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.
```

Helpfully, the error doesn't include where it's connecting.  Everything appears to be running OK, but this log spew is not ideal.

**Comment by reyjrar** [comment]
This is a result of GRAPHITE_URL defaulting to http://localhost:8000, setting it to port 80 solved the problem.

**Comment by DanCech** [comment]
@deniszh maybe we should change the default for that?

@reyjrar the error messages are more helpful in 1.1.2 which @deniszh is planning to release very soon.  I'd recommend updating to master if you're currently running 1.1.1 since there is a regression in carbon-cache that can result in significant delays writing metrics to disk.  As far as I'm aware everything in master right now will be backported to the 1.1.x branch for inclusion in 1.1.2

**Comment by deniszh** [comment]
@DanCech : Yes, I also had this idea - it's better to set it to port 80.

@reyjrar: yes, probably release it or this week or Monday/Tuesday. Or you can upgrade to latest commit of 1.1.x branch - 1.1.2 will be released from it.
