### ISSUE TITLE
Graphite on AWS EFS

### ISSUE THREAD

**Issue by yunstanford** [graphite-project/carbon#769]
Curious if anyone has deployed graphite on aws EFS, Does it perform well ? How does the IO performance look like ? What's the max IO tps does it support ?

**Comment by AsenZahariev** [comment]
+1 interested , also if anyone tried to autoscale  the stateless parts of graphite(relay and aggregation) ?

**Comment by josephryanwynne** [comment]
I don't have numbers to back this up at the moment so this is purely anecdotal... But I tried to switch to EFS from EBS to keep the setup as simple as possible. The goal was to eliminate the need for downtime when we had to scale our EBS volumes because at the time this couldn't be done without stopping the server and we were increasing disk usage quickly enough that it became annoying. We are pretty small so are running Grafana/Graphite/Carbon on a single node with one file system. Moving to EFS looked fine initially, but as the number of metrics being pushed into the system increased it became cripplingly slow (this is only managing application level metrics for < 100 nodes). We stopped depending on it entirely and I am now planning to switch back to EBS which at least gave us a usable system. It is now possible to resize an EBS volume without even rebooting so in our case EFS is now obviously an AWFUL choice for Graphite.

I **think** that the latency issues we have are due to the high number of small files required for whisper database format used by Graphite, and that the network overhead per file is what causes the problem. EFS is advertised as a shareable storage solution which scales automatically and supports high **aggregate** throughput and IOPS. Mounting from a single node doesn't seem to give ANY benefits and is currently performing worse than our old solution. My understanding is that spreading the iops over multiple nodes mounting that drive would probably work better but I am not sure how to make that happen with graphite/whisper and I have no intention of trying...
