### ISSUE TITLE
Carbon misses points

### ISSUE THREAD

**Issue by pinkynrg** [graphite-project/carbon#772]
In my `storage-schemas.conf` I do have a:

```bash 
[test]
pattern = ^test\.
retentions = 5m:1y,30m:10y
```

When I try to import data i get missing data: the inserted data goes only from ~2016/12 to ~2017/04 and from ~2018/03 to ~2018/05 (today).

<img width="2549" alt="screenshot 2018-05-10 17 34 59" src="https://user-images.githubusercontent.com/1474127/39897650-d813f102-5478-11e8-868b-55828056914b.png">

If I change the `storage-schemas.conf` to: 

```bash 
[test]
pattern = ^test\.
retentions = 5m:10y
```

everything works as expected and the missing data from ~2017/04 to ~2018/03 is now there (the gap in the image is actual data that i missed to read).

<img width="2515" alt="screenshot 2018-05-10 17 41 06" src="https://user-images.githubusercontent.com/1474127/39897785-7939b940-5479-11e8-96ef-03dd18471106.png">

I did try to delete and recreate the metric file so that the new retention plan was applied.

I checked the format of the input data and the missing data is formatted exactly as the correctly uploaded data.

**Comment by pinkynrg** [comment]
Actually I just found out that when using the first retention plan (`retentions = 5m:1y,30m:10y`):
- If I select points only from last 1 year I see everything as expected (which is all the data saved with 5 minutes granularity)
- If I select points beyond the 1 year line then I start seeing the empty gap (where by beyond I mean data saved with 30 minutes granularity). 

What am I supposed to do in order to see all data the correct way, meaning both the one with 5 minutes granularity and 30 minutes granularity?

**Comment by pinkynrg** [comment]
In this very case I have 
- data every 5 minutes after 2018-03-28 18:27
- data every 30 minutes before 2018-03-28 18:27

**Comment by DanCech** [comment]
Graphite will select a single aggregation for each series based on the time range, you will get back either 30-minute data or 5-minute data for the entire requested interval depending on the time period you're querying.

How did you create the whisper file?  If you created it by entering a value for each 30-minute period then @deniszh is absolutely correct that you would need to change the XFilesFactor to 1 before doing that, because whisper will see a single value and 5 nulls for each 30-minute period and discard it as invalid.

**Comment by DanCech** [comment]
5m:1y,30m:10y with xFileFactor to 1

**Comment by pinkynrg** [comment]
it worked but i had to set xfilesfactor = 0.0
