### ISSUE TITLE
graphite-web with tag support saved in hashed filename instead of the hierarchical file format 

### ISSUE THREAD

**Issue by caldavid** [graphite-project/carbon#813]
Hi,

I'm new to Graphite, and recently we are exploring the tag support, but found out the file hierarchy got changed, it seems that it's now using the encoded/hashed filename for each tagged metrics.

Is there a way i can keep the original filename format with tag enabled?

Thanks a lot!
David

**Comment by deniszh** [comment]
Hello David,

Yes, just set up `TAG_HASH_FILENAMES = False` in carbon.conf

**Comment by caldavid** [comment]
Hi Deniszh,

Thanks for your response!

I have disabled that already, the result turns to be only the filename got changed to human readable, but the file path became something like:  _tagged/001/221/_tagged.001.221.collectd_DOT_df_DOT_percent_bytes;tag1=value;tag2=value

Is that normal behavior?


Thanks a lot!
David

![screen shot 2018-09-18 at 2 52 48 pm](https://user-images.githubusercontent.com/27234781/45718689-cfa1cd00-bb52-11e8-84d0-ef406397ebb9.png)

**Comment by caldavid** [comment]
Would it be possible we can still keep the old file hierarchy? 

Like collect/server1/cpu/cpu-0-idle.... 

Your help is greatly appreciated!

David

**Comment by DanCech** [comment]
The old hierarchy cannot be used with tags because of the potential for cardinality problems when you have large numbers of series with the same name but different tags, ext2 and ext3 both run into issues with more than a few thousand files per directory.

If you're using tagged series, you'll have a better exploration experience with Grafana, which leverages the TagDB API to do auto-complete.  The graphite-web UI does not yet include that functionality.

**Comment by caldavid** [comment]
Gotcha.

Thanks for clarifying this.

Cheers,
David
