### ISSUE TITLE
Tests for s390 are broken

### ISSUE THREAD

**Issue by deniszh** [graphite-project/carbon#878]
Test for S390 became broken for all python versions.
For example, compare https://travis-ci.org/graphite-project/carbon/jobs/639241436 (successful) and https://travis-ci.org/graphite-project/carbon/jobs/645084882 (broken).
Unfortunately, I didn't find any reason for that.

@sangitanalkar - could you please check? Otherwise I think we need to revert https://github.com/graphite-project/carbon/pull/869

**Comment by sangitanalkar** [comment]
Hi @deniszh , yes checking it.

**Comment by deniszh** [comment]
Thanks a lot, @sangitanalkar !

**Comment by sangitanalkar** [comment]
Hi @deniszh 

The jobs for s390x at the mentioned [link](https://travis-ci.org/graphite-project/carbon/jobs/645084882) had `Permission denied` warnings like following:
```
WARNING: Building wheel for txAMQP failed: [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/52'
WARNING: Building wheel for coverage failed: [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/b0'
WARNING: Building wheel for mocker failed: [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/89'
WARNING: Building wheel for mmh3 failed: [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/38'
```

Checked the permissions of **"/home/travis/.cache/pip/wheels"** for amd64 and s390x in the travis image
For amd64:
```
$ ls -la $HOME/.cache/pip/wheels
total 12
drwxrwxr-x 3 travis travis 4096 Feb  7 05:14 .
drwxr-xr-x 5 travis travis 4096 Feb  7 05:14 ..
drwxrwxr-x 3 travis travis 4096 Feb  7 05:14 b9
```
For s390x:
```
$ ls -la $HOME/.cache/pip/wheels
total 6
drwxr-xr-x 10 root   root   10 Jan 20 13:03 .
drwxrwxr-x  5 travis travis  5 Jan 20 13:02 ..
drwxr-xr-x  3 root   root    3 Jan 20 13:03 66
drwxr-xr-x  3 root   root    3 Jan 20 13:03 9b
drwxr-xr-x  4 root   root    4 Jan 20 13:03 ad
drwxr-xr-x  3 root   root    3 Jan 20 13:03 ae
drwxr-xr-x  3 root   root    3 Jan 20 13:03 b5
drwxr-xr-x  3 root   root    3 Jan 20 13:02 c1
drwxr-xr-x  3 root   root    3 Jan 20 13:03 e5
drwxr-xr-x  3 root   root    3 Jan 20 13:02 f2
```

Since the owner was `root`, `travis` user was unable to modify the pip directory.
Cleared the cache at the beginning ([code changes](https://github.com/linux-on-ibm-z/carbon/blob/s390x-tests/.travis.yml#L64)) and the issue is fixed. 
Travis job for "python version 2.7 TOXENV=py27" ([link](https://travis-ci.com/linux-on-ibm-z/carbon/jobs/284811991)) has passed.

For travis jobs for python versions `3.6, 3.7, 3.8` ; two test case failures for `carbon.tests.test_client` and `carbon.tests.test_protobuf` are observed for both **amd64 as well as s390x.** 
Travis jobs log: https://travis-ci.com/linux-on-ibm-z/carbon/builds/147909666

**Comment by deniszh** [comment]
Hi @sangitanalkar ,
You're right, I'm completely missed permission errors. Thanks for fixing issues!

Another issues are something new, will fix it separately.
